### ISSUE TITLE
Creating only 16*16 favicon.ico 

### ISSUE THREAD

**Issue by andrey-hohlov** [haydenbleasel/favicons#101]
Hello again! 

WIndows 7, Gulp 3.9, using Gulp wrapper for favicons

When set `online: false` i get favicon.ico 16*16 (~0.5kb)
It's opening in browser, opening in windows image viewer. But hasn't preview image in folder.

Realfavicongenerator checker say:
```
favicon.ico seems corrupted or not in ICO format.
```
```
Some picture(s) are missing in favicon.ico:
16x16 picture
32x32 picture
48x48 picture
```

If set `online: true` we get favicon.ico 48*48 (with other sizes packed inside, weight about 14 kb). It passed realfavicongenerator test and also have preview image in folder.

**Comment by haydenbleasel** [comment]
Ahh that's true, we're only generating it at one size which isn't too good. I'm actually not sure how to composite multiple images into a single `.ico` file, or if Jimp even has that capacity. I'll need to look into this, or alternatively a PR is welcome from anyone that knows.

**Comment by andrey-hohlov** [comment]
Jimp don't support and don't want support.
lwip dont't support and don't want too: https://github.com/EyalAr/lwip/issues/38
Other that i find use ImageMagick or another dependence.

Maybe it's enough to support only 16x16 for old browsers (with no-retina screens they need only 16*16), because new browsers can use png.

**Comment by haydenbleasel** [comment]
Yep, we might have to do this for now.

**Comment by haydenbleasel** [comment]
@andrey-hohlov Stored this info in the README for now. We'll get back to it when possible.

**Comment by haydenbleasel** [comment]
Also, we've discussed this issue [here](https://github.com/oliver-moran/jimp/issues/87) too.

**Comment by wolfgang42** [comment]
I just found [kevva/to-ico](https://github.com/kevva/to-ico), which takes an `Array<Buffer>` of PNG images and seems to be working great.
