### ISSUE TITLE
Disabling web app focussed meta tags

### ISSUE THREAD

**Issue by mogusbi** [haydenbleasel/favicons#105]
Is there any way to generate icons without the added meta tags that are aimed more at web apps rather than websites, namely the mobile-web-app-capable, apple-mobile-web-app-* and application-name meta tags? There seems to be no configuration setting to disable these web app meta tags

**Comment by haydenbleasel** [comment]
Hey @mogusbi, not at the moment but if you've got a convincing use case then I'll be happy to explore a solution!

**Comment by mogusbi** [comment]
There must be more people out there than just me who just want to use this plugin to populate my bog-standard web page with the plethora of favicons out there and nothing more?

**Comment by haydenbleasel** [comment]
I don't see why you don't want them though. They're fantastic for icon validity and SEO, and you're getting them for free without doing any extra work. If there is a convincing argument towards opting out of HTML generation then this issue can be re-opened.

**Comment by mogusbi** [comment]
I'll try to word this a bit better than last time as I posted without really giving it too much thought.

Regarding the web app capable tags, some won't want them because if you add a page to your home screen, you don't automatically want it to be launched in a safari window that doesn't have any of the browser controls available.

As for the application title, the default for the appName param is null so if it stays null, it shouldn't just lump the meta tag in there any way without a title. Looking at W3C's documentation for the application-name meta tag, it states "If the page is not a Web application, the application-name metadata name must not be used". (https://www.w3.org/TR/html5/document-metadata.html#standard-metadata-names)

**Comment by haydenbleasel** [comment]
Hey @mogusbi, I definitely understand there's a potential need for opting out of HTML but I believe there is a better solution to these issues:

1) If you want to overwrite tags that generate e.g.  `<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">`, you can add `<meta name="apple-mobile-web-app-status-bar-style" content="default">` to your HTML and use `replace: false`.
