### ISSUE TITLE
[feature] pipe html file

### ISSUE THREAD

**Issue by perrin4869** [haydenbleasel/favicons#109]
Hi, I just finished setting up gulp to automate favicon generation, and all the images are created perfectly as expected :D 
In my setup, I am using jade as the express template engine, and so in order to use the html generated by this `favicons` module, it would be great to be able to pipe the generated html file through the `gulp-html2jade` plugin, and thus end up with a jade file to include in my templates. However, running `gulp-debug` I found that the `html` file is never piped. Is there any way you guys could enable the html file piping? Thanks!

**Comment by perrin4869** [comment]
Basically, this is what I want to achieve:

```javascript
return gulp.src(['client/img/icon.svg'])
	.pipe(svg2png())
	.pipe(favicons({
		...
		html: '../views/favicon.html',
		...
	}))
	.pipe(gulpif(/favicon\.html$/, html2jade()))
	.pipe(gulp.dest("public"));
```

**Comment by perrin4869** [comment]
ok I put together a quick implementation, will send pull request in a little while!

**Comment by haydenbleasel** [comment]
@perrin4869 Awesome, sounds good :)
