### ISSUE TITLE
gulp branch

### ISSUE THREAD

**Issue by perrin4869** [haydenbleasel/favicons#111]
Hi, I just noticed that you chose to separate `favicons` and `gulp-favicons` as just separate branches of the same repository. It is a very interesting choice, yet it is rather counter intuitive. For example, running `git diff master..gulp` would be rather meaningless. Is there any particular reason behind this choice?

**Comment by haydenbleasel** [comment]
Hey @perrin4869, yeah there is a reason. The entire API (normal and streamable) is located in the master branch (main module). Therefore, it's possible to use it in a streamable environment that isn't gulp with `require('favicons').stream`. A Gulp module is simply the implementation of my Streamable API with the word "gulp" on it, so the gulp branch is just a naming wrapper and allows me to publish to NPM as a seperate module (gulp-favicons vs favicons). See the [index.js](https://github.com/haydenbleasel/favicons/blob/gulp/index.js) file and you'll see what I mean.

**Comment by perrin4869** [comment]
Cool! Yeah I like for l how you combine the streaming api and the non streaming api. I'm just wondering if it makes sense semantically have separate branches rather than separate repos like most gulp plugins do. It's not really obvious at first

**Comment by perrin4869** [comment]
I'm saying it because of the semantics of the git diff statement I mentioned above

**Comment by haydenbleasel** [comment]
The only reason there is a gulp branch is so we can publish it on NPM. The branch has no real code or logic. It'll never update apart from bumping major version numbers of dependencies. Why do you need to diff the two branches?

**Comment by perrin4869** [comment]
Well the fact that you wouldn't want to do a diff is kinda the point... Most of the time branches are used to try new features, I just don't see a separate branch as a semantic way of representing a gulp plugin. A new repo with the exact same code in the master branch makes more semantic sense to me

**Comment by haydenbleasel** [comment]
Ahh okay, I get where you're going with it and it definitely makes more sense semantically to have it in a new GitHub repo, however I just fixed up all my modules and put them in this fashion as it's much easier to handle updates. I think if the Gulp version becomes vastly different from the parent, or we start getting a mad influx of PRs and new features then I'll split them.
