### ISSUE TITLE
Http:// becomes http:/ in generated html

### ISSUE THREAD

**Issue by joDelicious** [haydenbleasel/favicons#116]
Hi !

in the path option, i need to use an absolute url to reach the theme folder...
But the path I am writing in the favicons options gets transformed and looses a the second slash next to http in all generated html... w3c does not like that.

http://www.example.com/wp-content/themes/mytheme/assets/favicons

becomes :

http:/www.example.com/wp-content/themes/mytheme/assets/favicons

I've searched about it, yet haven't found any solution.
... any idea ? ...

Thank you...!
Johan

**Comment by haydenbleasel** [comment]
Argh this should have been fixed in #103. I'll look into it.

**Comment by joDelicious** [comment]
I don't know if it can be of any help but I'm using gulp-favicons 2.2.6

**Comment by haydenbleasel** [comment]
@joDelicious try removing Favicons completely (folder + package.json entry) and re-installing. Gulp wrapper uses the most recent Favicons version so that could be out of date on your machine.

**Comment by haydenbleasel** [comment]
Closing due to no response.
