### ISSUE TITLE
gulp-favicons/es5 requires favicons (es6)

### ISSUE THREAD

**Issue by rdallasgray** [haydenbleasel/favicons#117]
Hey, I'd submit a PR for this but there doesn't seem to be a separate GitHub repo for gulp-favicons.

Line 3 of gulp-favicons/es5.js requires "favicons" rather than "favicons/es5" -- which breaks under < Node 4.

**Comment by haydenbleasel** [comment]
https://github.com/haydenbleasel/favicons/blob/gulp/index.js

There is no gulp-favicons/es5, my bad. This file should be `favicons/es5`. PR gladly accepted.

**Comment by haydenbleasel** [comment]
Fixed in #118

**Comment by smesko85** [comment]
@haydenbleasel is this pushed to npm?

**Comment by haydenbleasel** [comment]
@smesko85 Published and did a version bump just in case. Try now.

**Comment by smesko85** [comment]
@haydenbleasel Wow, that was fast :) Thx. It is updated on npm :)
