### ISSUE TITLE
Override theme-color

### ISSUE THREAD

**Issue by michaelmior** [haydenbleasel/favicons#119]
Is there any way to change the value of the `theme-color` meta tag generated for Android? Actually, it feels really out of place for a library that generates favicons. In any case, I'd like to specify a different colour instead of the default white.

**Comment by haydenbleasel** [comment]
Hey @michaelmior, the `background` attribute propogates onto all colour-related fields including `theme-color`. I understand your thoughts on metadata generation and I'm currently musing over different methods of separating / handling this.

**Comment by michaelmior** [comment]
@haydenbleasel I assumed that was the case. However in my case, the background colour of my favicon does not match the colour I want to use as the `theme-color`. For now I'm just taking advantage of the fact that if there are multiple specifications of `theme-color` the first one seems to be used.
