### ISSUE TITLE
Generated favicons has a faint border

### ISSUE THREAD

**Issue by mattdrose** [haydenbleasel/favicons#123]
For some reason my generated favicons have a faint border at various points. I'm wondering if it has something to do with my source png.

Source:
<img src="https://cloud.githubusercontent.com/assets/1107972/14727628/f6fa1e60-07fa-11e6-9aa4-a2ab79c6ec22.png" width=150 height=150 title="Original"/>

Generated:
<img src="https://cloud.githubusercontent.com/assets/1107972/14727703/9755826e-07fb-11e6-8d4f-1a6dcfd829cb.png" width=150 height=150 title="Output"/>

**Comment by jwandrews** [comment]
@mattdrose is was due to the white stroke on the src image. removed stroke. fixed border ghosting.

**Comment by mattdrose** [comment]
Beauty! Thanks 👍
