### ISSUE TITLE
Adding mask icon for Safari pinned tab icons

### ISSUE THREAD

**Issue by BenjaminRCooper** [haydenbleasel/favicons#126]
Is it possible to look into adding the mask-icon for Safari, or is it out of scope?

`<link rel='mask-icon' href='my-icon.svg' color='white'>`

**Comment by haydenbleasel** [comment]
Hey @BenjaminRCooper, check out #61. We generate metatags for the icons we produce. We can generate that tag for sure, problem is we can't process SVG files :(

**Comment by colbyfayock** [comment]
hey @haydenbleasel - are you all able to support this now? or is the SVG support provided not necessarily what's needed for this feature?
