### ISSUE TITLE
Path for the HTML file

### ISSUE THREAD

**Issue by yoanmalie** [haydenbleasel/favicons#128]
Hello, 
I use gulp-favicons, and i want to know if it's possible to chose another directory for the index.html file ? If not, can you add this feature please ?

Thanks !

**Comment by dreamyguy** [comment]
Hi there @yoanmalie, 

It's possible to define another path to the `index.html` file, the path on one of my apps is `../../favicons/favicons.html`.

Take a look at what I did here: https://github.com/dreamyguy/gitinsight/tree/react. The project is under development but the **favicons** task is working fine. 🚀 

* [The favicons task](https://github.com/dreamyguy/gitinsight/blob/react/gulp/tasks/favicons.js)
* [The centralised configuration](https://github.com/dreamyguy/gitinsight/blob/react/gulp/config-template.json#L161-L181)
* [The html template and icon.png](https://github.com/dreamyguy/gitinsight/tree/react/src/base/favicons)

Cheers! ✨

**Comment by haydenbleasel** [comment]
Thanks @dreamyguy :+1:

**Comment by dreamyguy** [comment]
Np @haydenbleasel, couldn't live without your take on `favicons`. Cheers!
