### ISSUE TITLE
TypeError on require('favicons')

### ISSUE THREAD

**Issue by Sizuko** [haydenbleasel/favicons#129]
I've got this error : 

> Uncaught TypeError: fs.readdirSync is not a function

It triggers on my require of favicons and i don't know how to fix it. I didn't find any other issue talking about it, so if anyone have an idea it will be nice.

**Comment by haydenbleasel** [comment]
Hey @Sizuko, that's very strange. What version of node are you running? `node -v`

**Comment by Sizuko** [comment]
My bad, i try to import it on client side instead of server side.

**Comment by Nabilamehjabin** [comment]
Restart for progress
