### ISSUE TITLE
Generating 1.91:1 or 1:1 ratio image for Facebook Open Graph meta tag

### ISSUE THREAD

**Issue by jwandrews** [haydenbleasel/favicons#139]
According to Facebook's own [Sharing Best Practices](https://developers.facebook.com/docs/sharing/opengraph/object-properties) regarding the og:image tag, the images should be of ratio 1.91:1 or similar to limit cropping.

They suggest an optimal resolution of 1200x630 pixels. The generated open-graph.png (1500x1500 pixels) icon is much too large and is cropping a lot of the content of my source file to the point of it being unusable. Interesting note that it is also 1:1 ratio, which is the suggested ratio for a Facebook "Game icon" at 600x600 pixels.

I'm wondering if there should be an option to generate a 1.91:1 or a 1:1 ratio image for the open graph meta tag.

Thoughts?

**Comment by haydenbleasel** [comment]
Come to think of it, I don't think either of these should be in Favicons. These cover photos are meant to be proper images rather than your logo.

**Comment by jwandrews** [comment]
This is what I thought too as I was looking into this. It's weird that a favicon package would be generating this image. It's a different use case and purpose. I have turned the og generation off for now and just using a regular image and not the generated file.

**Comment by haydenbleasel** [comment]
I'll remove this on the next publish.

**Comment by haydenbleasel** [comment]
Removed in `favicons@4.7.4`
