### ISSUE TITLE
Further lock-down version of svg2png

### ISSUE THREAD

**Issue by jonathanq** [haydenbleasel/favicons#153]
The author of svg2png released a new version (3.1.1) which requires Node 6+ (https://github.com/domenic/svg2png/issues/59).  Due to the way NPM is parsing the version restriction on favicons (svg2png ^3.0.1) - we are getting 3.1.1 pulled in and it is failing to install on Node 5 boxes.

Given that the Readme for favicons states it works on 4+.  Can you lock down the svg2png version further to prevent 3.1.1 getting pulled in?

**Comment by santo74** [comment]
Maybe this is also the cause of [https://github.com/haydenbleasel/favicons/issues/152](https://github.com/haydenbleasel/favicons/issues/152) when not using Node 6+ (see last comments) ?

**Comment by jverghese** [comment]
This is breaking builds for me as well. Submitted pr https://github.com/haydenbleasel/favicons/pull/154 to fix this.

**Comment by haydenbleasel** [comment]
Merged #154 and pushed to NPM.
