### ISSUE TITLE
Generated favicon.ico is malformed

### ISSUE THREAD

**Issue by jraoult** [haydenbleasel/favicons#155]
Following the discussion here: https://github.com/kevva/to-ico/issues/8, it appears the introduced `.ico` generation in #137 is not working properly. It seems like it is a problem with the images order in the `.ico` file.

I could reproduce in Chrome and Firefox.

**Comment by jraoult** [comment]
@haydenbleasel I created a PR for a version upgrade of `to-ico`: https://github.com/haydenbleasel/favicons/pull/156

**Comment by haydenbleasel** [comment]
Merged 👍
