### ISSUE TITLE
killed when run task in gulp

### ISSUE THREAD

**Issue by Muskos** [haydenbleasel/favicons#174]
Hi.
I have some problem. 
When i run gulp task on local serve - everything allright.
When i try to run task on production i get error https://yadi.sk/i/xty-VN1s3Gtf5L (left side production).
How can i debug this error?

**Comment by Muskos** [comment]
`gulp.task("****_favicon", function () {
    return gulp.src("***/img/favicon/favicon.png").pipe(favicons({
        appName: "****",
        appDescription: "****",
        developerName: "****.ru",
        developerURL: "//***.local.ru/****",
        background: "#fff",
        lang: "ru-RU",
        path: "/dist/***/favicon/",
        url: "https://***/***",
        display: "standalone",
        orientation: "portrait",
        start_url: "/?homescreen=1",
        version: 1.0,
        logging: true,
        online: false,
        html: "index.html",
        pipeHTML: true,
        replace: true
    }))
    .on("error", gulpUtil.log)
    .pipe(gulp.dest("../www/dist/***/favicon/"));
});`

**Comment by dangreen** [comment]
@Muskos I think your production server have RAM usage limitations.

**Comment by Muskos** [comment]
@dangreen yes allright thx
