### ISSUE TITLE
Error `spawn ENOENT`

### ISSUE THREAD

**Issue by thasmo** [haydenbleasel/favicons#23]
Running favicons in my `images` gulp task outputs the following:
```
[18:01:04] 'images' errored after 577 ms
[18:01:04] Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

Any idea why that's happening?

**Comment by thasmo** [comment]
Hold on, probably a problem with my IM installation. I'll check.

**Comment by thasmo** [comment]
Nah, error still pops up. :l

**Comment by haydenbleasel** [comment]
@thasmo It's a young module so it's probably my fault haha. Can I see your gulpfile?

**Comment by thasmo** [comment]
Sure, my gulpfile includes task files using `require('require-dir')('./task/default');` and my `images` task is here:
```js
var gulp = require('gulp'),
	favicons = require('favicons');

gulp.task('images', function(cb) {
	favicons({
		files: {
			src: 'source/image/appearance/tile.png',
			dest: 'public/'
		},
		settings: {
			appName: 'gulp.js Boilerplate'
		}
	}, cb);
});
```

**Comment by haydenbleasel** [comment]
@thasmo You know there's a [Gulp version](https://www.npmjs.com/package/gulp-favicons) of this module right? Makes it so much easier.

**Comment by thasmo** [comment]
Oh, no I didn't - I'll try it.

**Comment by haydenbleasel** [comment]
@thasmo No worries, if you have a problem with that plugin still, open an issue on the Gulp branch and we'll sort it out!
