### ISSUE TITLE
Publish Gulp plugin as a separate repository

### ISSUE THREAD

**Issue by addyosmani** [haydenbleasel/favicons#26]
In the Node ecosystem, the majority of build system plugins are hosted in their own separate repositories. This makes it easier to discover them (We've had some trouble going back and forth between the module and Gulp file given branching strategies). 

Would you consider pushing the Gulp plugin to a gulp-favicons repo?

**Comment by haydenbleasel** [comment]
I was hoping to group them together (as every gulp / grunt implementation is just a wrapper around the main module) but I think you're right, and if it makes it easier for anyone then it's definitely worth doing. I'll split out all my modules today :)
