### ISSUE TITLE
Need characters to come across unescaped

### ISSUE THREAD

**Issue by germanny** [haydenbleasel/favicons#32]
Hi!

I've run into an issue with generating a full path to the icons that contains a string like `<?php echo ... ?>`. Those `<>` should come across unescaped, but the path written to `favicons.php` is coming out as `&lt;?php echo ... ?&lt;/`.

Just to be clear, I'm not expecting it to run the PHP script. It should simply write it exactly as entered into the `iconsPath` option.

Thanks!
Jen
@germanny

**Comment by haydenbleasel** [comment]
Hey @germanny, this should be solved now as of #42.

**Comment by germanny** [comment]
Thank you!!
