### ISSUE TITLE
Transferred repos

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/favicons#33]
@jessaustin Sorry to be a pain, but we were in the middle of phasing out `rfg-api` and `real-favicon` repositories to keep things simple. This means your PR is gone, but it can quickly be rewritten for this repo - same code more or less. Sorry about that!

**Comment by jessaustin** [comment]
So I should make an equivalent PR for this module? If so I'll probably also abstract out the config interpretation in addition to the icon stream.

**Comment by haydenbleasel** [comment]
If possible, yeah :) Appreciate your time in this so far!
