### ISSUE TITLE
400: could not publish request to the RealFaviconGenerator API.

### ISSUE THREAD

**Issue by webchaz** [haydenbleasel/favicons#36]
According to their docs we need an api_key, but I don't see an api_key config option.  I'm not sure if this is the issue here exactly, but the error above is what's being returned.

**Comment by dmnsgn** [comment]
Creating my API key and changing it directly into the configuration json had no effect in my case.

**Comment by haydenbleasel** [comment]
@phbernard Any ideas matey?

**Comment by jamesryanbell** [comment]
FYI: This only seems to be an issue when inline images are used, if you pass an image URL then the script works correctly.

**Comment by haydenbleasel** [comment]
@jamesryanbell Ahh okay. The module inlines images automatically so we'll need to allow inline images too.

**Comment by phbernard** [comment]
Not sure to understand what's wrong. Do you have an error message with the 400 itself?

I realize the API gives the message along with the status. Some HTTP libs don't return it because it's not in the response body. @haydenbleasel, could it help if the API would return a JSON document, along with the 400? (the `error` case described in the <a href="http://realfavicongenerator.net/api/interactive_api">interactive API</a>).

**Comment by Mashi** [comment]
Trying to run via node with:
```javascript
var favicons = require('favicons');
var options = { files: { src: './src/img/logo.png', dest: './build/' } };
favicons(options);
```
but getting: 400: could not publish request to the RealFaviconGenerator API.

**Comment by jessehattabaugh** [comment]
I get this error when calling like so;

```js
var config = {};
config.srcPath = path.join(__dirname, srcDir);
config.destPath = path.join(__dirname, destDir);

favicons({
    files: {
      src: path.join(config.srcPath, 'favicon.png'),
      dest: config.destPath
    },
    icons: {
      opengraph: false
    }
  }, function (error, metadata) {
    if(error) {
      console.error(error);
    }
    console.log('favicon task finished');
  });
```

**Comment by jessehattabaugh** [comment]
Also fails if I inline the base64 data myself like so
```js
var iconFile = path.join(config.srcPath, 'favicon.png');
  fs.readFile(iconFile, function (err, data) {
    favicons({
      files: {
        src: path.join(config.srcPath, 'favicon.png'),
        dest: config.destPath
      },
      icons: {
        opengraph: false
      },
      favicon_generation: {
        master_picture: {
          type: 'inline',
          content: new Buffer(data).toString('base64')
        }
      }
    }, function (error, metadata) {
      if(error) {
        console.error(error);
      }
      console.log('favicon task finished');
    });
  });
```

**Comment by jessehattabaugh** [comment]
adding an api_key didn't help

**Comment by brianberlin** [comment]
In my case, I got this error because the png i was trying to use was not large enough. Since the callback doesn't send back the original error message, its difficult to troubleshoot.

**Comment by haydenbleasel** [comment]
Hey everyone, sorry for the delay on this - I've been doing uni exams. @brianberlin made a PR so we can return the original error message on non-200 cases, so can anyone who had an error update and re-run, see what the go is?

**Comment by haydenbleasel** [comment]
Also judging from the comments, I don't think the API key is the problem (everyone is using the same one - it's allocated to the module) so there's probably just a variety of image-based problems.

**Comment by haydenbleasel** [comment]
@webchaz @dmnsgn @jamesryanbell @Mashi @jessehattabaugh 

Hey everyone. Sorry this issue has been open so long. @brianberlin made a PR so we can return the original error message on non-200 cases, so can anyone who had an error update and re-run, see what the go is? Judging from the comments, I don't think the API key is the problem (everyone is using the same one - it's allocated to the module) so there's probably just a variety of image-based problems.

Let's get this problem sorted out.

**Comment by haydenbleasel** [comment]
@webchaz @dmnsgn @jamesryanbell @Mashi @jessehattabaugh @phbernard @brianberlin Hey all, I'm merging this issue into Favicons 4.0. I'd love for you to join in the discussion: #51
