### ISSUE TITLE
Local generation of favicons

### ISSUE THREAD

**Issue by garygreen** [haydenbleasel/favicons#44]
Just browsing thru the issues and there's mentions of ImageMagick, gm but I don't see anywhere in the source where it supports generating images locally? Is this purely reliant on generating thru RealFaviconGenerator service? Would be nice to support generating the different sizes locally....

**Comment by haydenbleasel** [comment]
@garygreen Yeah versions 1 and 2 of favicons used Image/Graphics Magick to produce the icons, however I partnered up with RealFaviconGenerator for version 3 so favicons is simply a wrapper for their service. This occurred for a few reasons, the main being that I can focus on maintaining a node module while they can focus on maintaining the evolving icon standards.

We have heard this issue about local generation and we're looking into it at the moment - we have some ideas.

**Comment by garygreen** [comment]
Relying on another service and access to the internet for your build tool to function is a big turn off for me. But I understand it's difficult to maintain with the evolving standards. Would love to see local generation back in :-)

**Comment by Maximilianos** [comment]
There is also this option for local image generation: https://github.com/oliver-moran/jimp
claims to be node JS only. Not requiring Image/Graphics Magick would be pretty sweet

**Comment by haydenbleasel** [comment]
@Maximilianos Jimp seems pretty cool. I'm tossing up between that or [Sharp](https://github.com/lovell/sharp). Dependency on libvips is a tad annoying but still. Thoughts?

**Comment by haydenbleasel** [comment]
@garygreen @Maximilianos @tlvince Hey all, merging this issue into Favicons 4.0. I'd love for you to join in the discussion: #51
