### ISSUE TITLE
Zlib error

### ISSUE THREAD

**Issue by senthanal** [haydenbleasel/favicons#45]
Hi, 
I've a strange issue while running gulp tasks on the CI(Linux machine). It continues to break up in the middle exactly at the favicon generation task. Follows, the error message,
<pre>
<code>
events.js:85 
     throw er; // Unhandled 'error' event
Error: invalid distance too far back
    at Zlib._handle.onerror (zlib.js:366:17)
</code>
</pre>

Seems some problem with Zlib module(http://stackoverflow.com/questions/27039415/error-when-using-zlibinflate-invalid-distance-too-far-back).

Though, I never get such error at my dev(windows machine) environment. Any ideas?

By the way, thanks for the excellent favicon npm module. Its very helpful.

**Comment by haydenbleasel** [comment]
Hey @senthanal, merging this issue into Favicons 4.0. I'd love for you to join in the discussion: #51
