### ISSUE TITLE
Switch to unzip2

### ISSUE THREAD

**Issue by davewasmer** [haydenbleasel/favicons#47]
It appears that the [`unzip` module](https://github.com/EvanOxfeld/node-unzip) is abandoned. When using this module, I periodically get `invalid signature` errors, which appear to originate from the `unzip`. Looking through the [unzip issues](https://github.com/EvanOxfeld/node-unzip/issues) shows several other folks with similar issues.

It looks like a fork has fixed at least some of these issues: [`unzip2`](https://github.com/glebdmitriew/node-unzip-2). It might be worth switching over.

It looks like it maintains the same API. I would submit a PR with the change, but it looks like you are monkey-patching the `unzip` stream's `.emit()` function, so I wanted to check with you first.

**Comment by haydenbleasel** [comment]
@davewasmer To be honest, I haven't touched this module's code in a while - a couple of other contributors implemented the unzip functionality that broke things and I haven't had the time to fix anything up.

That being said, if you reckon you can fix the unzip issues by switching to the fork that's cool with me, but it looks like his fork hasn't got any of the updates from the original repo's 0.1.10 and 0.1.11 updates.

**Comment by haydenbleasel** [comment]
Hey @davewasmer, merging this issue into Favicons 4.0. I'd love for you to join in the discussion: #51
