### ISSUE TITLE
Add SVG support

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/favicons#53]
SVG support can be easily implemented if we find a pure-JS Node library that handles SVG to PNG conversion with no external dependencies.

**Comment by cloud-walker** [comment]
What about [librsvg](https://www.npmjs.com/package/librsvg)?

**Comment by haydenbleasel** [comment]
@cloud-walker relies on the librsvg package from Brew / Yum / Apt-Get. The solution needs to be 100% JS. Good find though, probably the closest solution thus far.

**Comment by haydenbleasel** [comment]
- ~~https://www.npmjs.com/package/svg2png~~ (needs PhantomJS)
- ~~https://www.npmjs.com/package/svg-to-png~~ (needs Imagemin & PhantomJS)
- ~~https://github.com/shakiba/svgexport~~ (needs PhantomJS)
- ~~https://www.npmjs.com/package/librsvg~~ (needs native dependencies)

No luck so far :(

**Comment by langri-sha** [comment]
Would installing optional (native) dependencies be acceptable?

**Comment by haydenbleasel** [comment]
@langri-sha possibly, what do you have in mind?

**Comment by langri-sha** [comment]
Well, `2gis/node-rsvg` seems to hit home pretty close, in the here and now. Would it be acceptable to add it as a [optional dependency](https://docs.npmjs.com/files/package.json#optionaldependencies) and perform a runtime check when a SVG asset is provided?

I'm just assuming there is a large portion of users which already have their logo vectors provided in SVG, who are then exporting a PNG to be able to use the package.

**Comment by haydenbleasel** [comment]
@langri-sha I love the look of that module but it definitely requires the native deps. I want to compromise but Google's planning on using this for WSK and their main issue was with native deps. Plus, I'm aiming for a pure JS build system hence the switch to Jimp.

**Comment by haydenbleasel** [comment]
Documented in the README for now, we'll come back to this when possible.

**Comment by haydenbleasel** [comment]
Update: If you're using Gulp, you can pipe from `svg2png` for now.

**Comment by strarsis** [comment]
Why is a pure JavaScript solution for SVG rendering required?
Isn't this a build tool and usually run on nodejs (with bindings)?

**Comment by stavarengo** [comment]
Weird thing, in my machine Ubuntu 15.10 with Node 6.6.0 e npm 3.10.3 it works when I use an SVG image.
But, at my server machine (in the cloud) it does not work. The server machine is a Ubuntu 14.04 with Node 6.6.0 and npm 3.10.3.

The only diff between these machines is the Ubuntu version.
You guys have any ideia why this happens?

**Comment by strarsis** [comment]
@haydenbleasel: JavaScript SVG solution: https://github.com/canvg/canvg

**Comment by Hypnosphi** [comment]
@strarsis you would need [node-canvas](https://github.com/Automattic/node-canvas) for that, which uses native package cairo

**Comment by Hypnosphi** [comment]
What about [sharp](https://github.com/lovell/sharp)?

> Most modern 64-bit OS X, Windows and Linux (glibc) systems running Node versions 4, 6, 8 and 10 do not require any additional install or runtime dependencies.

**Comment by RamilMamedo** [comment]
What about this? https://github.com/neocotic/convert-svg

**Comment by JoshuaWalsh** [comment]
@Hypnosphi It appears that as of #221 Sharp is now used.

**Comment by Marr11317** [comment]
So if sharp is now used, what is the status of 

> Why are you missing certain favicons?

**Comment by mrkvon** [comment]
I can confirm that, with the latest version today&mdash;7.2.0&mdash;SVG used as `src` seems to work fine (in my case, provided as a `Buffer`).
