### ISSUE TITLE
Consider adding silhouette ability for Windows

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/favicons#58]
To reflect functionality provided by the RFG API, we'd need #53 or a library like potrace that traces rasterised image types to vectors. Pure-JS only, as usual.

**Comment by haydenbleasel** [comment]
[AutoTrace](https://www.npmjs.com/package/autotrace) should do the trick...

**Comment by haydenbleasel** [comment]
Documented in the README for now, we'll come back to this when possible.

**Comment by ArmorDarks** [comment]
How about ability to provide in addition to base rarster image prepared manually `svg`?

Personally I didn't like idea of vectorization based on raster anyway... To many rough edges.

**Comment by dangreen** [comment]
@ArmorDarks ["Partial offline SVG support"](https://github.com/haydenbleasel/favicons/pull/148) ?

**Comment by ArmorDarks** [comment]
@dangreen Thanks for pointing out, didn't see that :)

**Comment by dnorthup-ums** [comment]
If you need to output SVG (using SVG as input) you could use [SVG.js](https://github.com/svgdotjs/svg.js)...
