### ISSUE TITLE
Add El Capitan favicon support

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/favicons#61]
Like #58, to reflect functionality provided by the RFG API, we'd need #53 or a library like potrace that traces rasterised image types to vectors. Pure-JS only, as usual.

```
<link rel="mask-icon" href="website_icon.svg" color="red">
```

**Comment by haydenbleasel** [comment]
Documented in the README for now, we'll come back to this when possible.

**Comment by NetOperatorWibby** [comment]
Have you seen this? https://github.com/btmills/geopattern

**Comment by mahnunchik** [comment]
@haydenbleasel any news?

**Comment by dnorthup-ums** [comment]
If you need to output SVG (using SVG as input) you could use [SVG.js](https://github.com/svgdotjs/svg.js)...

**Comment by uuf6429** [comment]
How about 'partial support' in case where the svgs are already provided in the sources?
