### ISSUE TITLE
Add ES6 -> ES5 build step

### ISSUE THREAD

**Issue by davewasmer** [haydenbleasel/favicons#64]
This module is written in ES6 (yay!), but is released as ES6 as well, rather than compiling to ES5 first. This is problematic for compat purposes: node 0.12.x, widely used in the wild, doesn't support most of the ES6 syntax used by this module. That means that consuming code must include it's own transpilation step.

A better approach would be to compile this ES6 to ES5 during pre-publish, and use a combination of `.gitignore` and `.npmignore` to ensure that the compiled ES5 files aren't committed to the repo, and the source ES6 files aren't shipped with the npm release.

**Comment by haydenbleasel** [comment]
Ughhh I hoped nobody would pick up on this and just upgrade to Node 4.x haha. But yeah you're right. Do you reckon you could help out with a PR on this? I'm not sure the best way of doing it. Otherwise I can probably figure it out next week sometime.

**Comment by davewasmer** [comment]
Sorry :wink:

Happy to PR if I can find the time. I'd suggest something like https://github.com/jmeas/es6-node-boilerplate - I've used similar boilerplates in the past. Basic idea is to setup gulp (or something similar) to compile (as well as test/lint/code coverage if you'd like) everything from `src/` into `dist/`. Then you `.gitignore` the distributed files, and `.npmignore` the source files.

Can't promise when I'll get to it exactly, but hopefully soon ish

**Comment by haydenbleasel** [comment]
Hey @davewasmer, fixed in `favicons@4.2.0`. Just `require('favicons/es5')`. The helpers file is still in ES6 though. Not sure how to go about that.

**Comment by davewasmer** [comment]
I haven't been able to test it yet, but my guess is that won't work. Unless the consuming app has done something like `require('babel/register')`, when your `es5.js` file attempts to `require('./helpers')`, it's going to try to parse that file, and will hit errors on the es6 syntax.

**Comment by haydenbleasel** [comment]
@davewasmer I've updated Favicons to use an ES5 helpers file until ES6 is completely supported.
