### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by davewasmer** [haydenbleasel/favicons#65]
It would be helpful if, when a new version is released, a git tag is created for that version and published to Github as well. It's helpful if you want to go back through old versions of the code based on what older version your own app/consuming library might be on.

**Comment by haydenbleasel** [comment]
Hey Dave, yeah I agree - I was pretty casual with this from the start but things are picking up quickly. I'll add tagging this week :)

**Comment by haydenbleasel** [comment]
Hey @davewasmer, I'll start tagging each minor release from now on. `v4.1.0` and `v4.2.0` are up.
