### ISSUE TITLE
android-chrome-manifest.json vs. manifest.json

### ISSUE THREAD

**Issue by di5abled** [haydenbleasel/favicons#67]
Hello,

you are generating the file `manifest.json` but in the generated HTML you reference `android-chrome-manifest.json` guess one of this two names is wrong? :)

**Comment by haydenbleasel** [comment]
Hey @di5abled, yes that was a recent change, we must have missed updating the HTML reference - nice find! I see you've forked and fixed it, how about a PR? Thanks :+1:

**Comment by haydenbleasel** [comment]
Fixed in `favicons@4.2.0`.
