### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/favicons#69]
Originally opened by @vn38minhtran

- Missing apple-touch-startup-image-1024x748.png
- Missing apple-touch-startup-image-2048x1496.png

**Comment by haydenbleasel** [comment]
> The generated markup for some of the graphics such as-

```
href="assets/img/favicon/apple-touch-startup-image-2048x1496.png"
href="assets/img/favicon/apple-touch-startup-image-1024x748.png"
```

> differ from the file names which are -

```
apple-touch-startup-image-1496x2048.png
apple-touch-startup-image-748x1024.png
```

> These specifc images are also rotated 90 degrees. Am I missing something? All the rest work fine.

**Comment by alanontheweb** [comment]
Yeah, it's an easy fix in html.json. I just reversed the file name in my fork. Thanks!

**Comment by haydenbleasel** [comment]
@alanontheweb Awesome. I'm not sure which way around the numbers are meant to be, but if you figure out, can you submit a PR? :)

**Comment by alanontheweb** [comment]
Sure thing. Let me investigate to make sure all the orientations are set right and I'll do a PR.

**Comment by haydenbleasel** [comment]
@alanontheweb Thanks mate. If you run `npm test` it will run the RFG generator too and that should show the correct output in the `test/images-online` folder.

**Comment by haydenbleasel** [comment]
Closing this for #107
