### ISSUE TITLE
Legacy issues

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/favicons#70]
Originally opened by @gauntface:

- [x] On Chrome stable, because there is no there is no icon supplied. The manifest is only picked up in Chrome Beta.
- [ ] Also had some issues with iOS 8 (the app icon and start up screen weren't getting used)

(Not sure if these still apply).

**Comment by phbernard** [comment]
The manifest is used by the latest versions of Android Chrome. Previous versions use the 192x192 PNG icon.

**Comment by haydenbleasel** [comment]
@phbernard Awesome :) Any ideas on the iOS8 icon?

**Comment by haydenbleasel** [comment]
Closing this issue, someone can raise it again if it's still a problem.
