### ISSUE TITLE
"mobile-web-app-capable" not showing

### ISSUE THREAD

**Issue by johnholtripley** [haydenbleasel/favicons#76]
I was going to create a pull request to add in `<meta name='mobile-web-app-capable' content='yes'>` but I can see it in config/html.json within the android definition.
In the generated html (with the gulp-favicons wrapper), I get the `<meta name="apple-mobile-web-app-capable" content="yes">` but not the android version.
Is this a bug?
thanks

**Comment by haydenbleasel** [comment]
Hey @johnholtripley, can I see your Gulpfile for this? I can't see an error in the configuration so I might have overlooked something during execution.

**Comment by johnholtripley** [comment]
Hi, yeah, the full gulp file is at https://github.com/johnholtripley/Autumn-Earth/blob/master/site/gulpfile.js
Thanks

**Comment by haydenbleasel** [comment]
Hey @johnholtripley, just realized the reason for this is because RealFaviconGenerator (the online version) doesn't generate this meta tag. @phbernard Thoughts on this?

**Comment by johnholtripley** [comment]
hi @haydenbleasel - that makes sense, thanks for raising it with RFG

**Comment by phbernard** [comment]
Yep, thank you for raising this! ;) It's https://github.com/RealFaviconGenerator/realfavicongenerator/issues/205
