### ISSUE TITLE
Manifest.json appears to be incomplete

### ISSUE THREAD

**Issue by emaildano** [haydenbleasel/favicons#79]
The file stops at `android-chrome-192x192`. Is that normal?

I'd like to use this file to build a `foreach` to dynamically bring in the listed favicons.

Here's the manifest.json build I have for example:

```json
{
  "name": null,
  "display": "standalone",
  "orientation": "portrait",
  "icons": [
    {
      "src": "/android-chrome-36x36.png",
      "sizes": "36x36",
      "type": "image/png",
      "density": "0.75"
    },
    {
      "src": "/android-chrome-48x48.png",
      "sizes": "48x48",
      "type": "image/png",
      "density": "1.0"
    },
    {
      "src": "/android-chrome-72x72.png",
      "sizes": "72x72",
      "type": "image/png",
      "density": "1.5"
    },
    {
      "src": "/android-chrome-96x96.png",
      "sizes": "96x96",
      "type": "image/png",
      "density": "2.0"
    },
    {
      "src": "/android-chrome-144x144.png",
      "sizes": "144x144",
      "type": "image/png",
      "density": "3.0"
    },
    {
      "src": "/android-chrome-192x192.png",
      "sizes": "192x192",
      "type": "image/png",
      "density": "4.0"
    }
  ]
}
```

**Comment by haydenbleasel** [comment]
Hey @emaildano, the [icons.json](https://github.com/haydenbleasel/favicons/blob/master/config/icons.json) file currently defines 6 icons, ending in `192x192`. This is correct according to my knowledge, unless I'm missing some icons completely or there's been an update. Are we missing something?

**Comment by haydenbleasel** [comment]
I've verified that it matches the output from RFG and what's states in Google's [documentation](https://developer.chrome.com/multidevice/android/installtohomescreen).

**Comment by emaildano** [comment]
@haydenbleasel, I should clarify. The `manifest.json` file I'm referring to one from my build.

After `gulp favicons`, that file is created and it only has the icons mentioned above. It'd be great if the file included apple, firefox, etc. related icons so I could bring them all in dynamically.

Right now I'm not passing any settings into the gulp task except the image file path, so it should all be default.

**Comment by haydenbleasel** [comment]
It could be possible to add more icons to this, although I'd need to refer to @phbernard about what the standard is at this point in time.

Philippe, the W3C draft for [manifest.json](https://w3c.github.io/manifest/) looks like it supports stuff like splash screen icons and potentially other icons.

**Comment by phbernard** [comment]
As far as I know, Android Chrome is the only browser that supports the JSON manifest, as described by the W3C. [Chrome extensions](https://developer.chrome.com/extensions/manifest) and [Firefox apps](https://developer.mozilla.org/en-US/Apps/Build/Manifest) also rely on a JSON manifest, but there are two different formats.

[Most recent Android Chrome supports splash screen](https://developers.google.com/web/updates/2015/10/splashscreen). It does so by re-using the icons and background color declared in the manifest (*not* the `splash_screens` of the W3C manifest).

Therefore, at the moment, I see no reason to not follow [Google's template for `manifest.json`](https://developer.chrome.com/multidevice/android/installtohomescreen#manifestmetadata).

**Comment by haydenbleasel** [comment]
@emaildano For argument's sake, what would your suggested manifest look like?

**Comment by emaildano** [comment]
@haydenbleasel like your [icons.json](https://github.com/haydenbleasel/favicons/blob/master/config/icons.json) file.

A file with which I could parse and display all the icons I need in the head.

Right now the only file I get is the manifest.json build file which has all the `android-chrome` related icons but not the other icons mentions in html.json, icons.json, etc.

Maybe I'm missing how to create a build file with those included?

**Comment by haydenbleasel** [comment]
@emaildano I'm curious what this would look like so if you'd like to set up a PR then I'll take a look.

**Comment by haydenbleasel** [comment]
Will re-open when a PR or complete suggestion is provided.
