### ISSUE TITLE
Asset versioning

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/favicons#80]
See: https://github.com/RealFaviconGenerator/gulp-real-favicon/issues/5

- Timestamp
- File Hash (https://nodejs.org/api/crypto.html#crypto_crypto_createhash_algorithm)

Refer to RFG API for implementation style.

**Comment by strarsis** [comment]
So those links to extra gulp plugins indicate that URL-based cache busting is rather the job of a different/extra plugin (I agree btw)?

With best regards

**Comment by haydenbleasel** [comment]
@strarsis I wish it could be, but since Favicons generates HTML and files but only returns files to the stream, only the files will get versioned if we use a seperate gulp plugin i.e. The HTML links will be incorrect.

**Comment by strarsis** [comment]
Also, for example, I would like to just include the generated HTML in a Jade layout template:
````
include ./generated/favicon.html
````

**Comment by haydenbleasel** [comment]
@strarsis Actually that's a good idea. Post `favicons` generation, you can use something like `gulp-useref` + `gulp-rev` + `gulp-rev-replace` to sort this stuff out. I've done something similar in [Catalyst](https://github.com/haydenbleasel/catalyst/blob/master/gulpfile.js) if that helps. Nice work.
