### ISSUE TITLE
Allow the stream API to accept a callback for html

### ISSUE THREAD

**Issue by jraoult** [haydenbleasel/favicons#83]
The now "deprecated" `gulp-favicons` allowed to pass a callback as last arguments that was getting the HTML code as a string so that it could be manipulated and "manually" inserted in the web page (feature introduced here: https://github.com/haydenbleasel/gulp-favicons/commit/bccb0bcc6c24a9034d17de9371beb2eb14986a47)

It seems we lost this feature during the merge of the stream features to the main project.

**Comment by haydenbleasel** [comment]
Hey @jraoult, sorry for missing this feature, I'll get it back in ASAP. Out of curiosity, what was the main issue with the streaming API that means you still need that callback? i.e. why not use the typical:

```
var favicons = require("gulp-favicons");

gulp.task("default", function () {
    gulp.src("logo.png").pipe(favicons({
        // configuration...
        html: "index.html"
    })).pipe(gulp.dest("./"));
});
```

**Comment by jraoult** [comment]
Hey, nothing wrong with the "file" approach but I need to control the injection of the meta info into the page. To do that I use my own injection methods therefore I would need the string value of this block. I could indeed make it write in a temporary file then read this file to extract the metas but it is not really "gulpy" :)

**Comment by jraoult** [comment]
Actually I'm happy to write a patch for that if you want. I would just need your inputs in terms of API: overload the `html` config property to accept a callback or pass the callback as a third argument to like `stream(options, (htmlCode) => {})`

**Comment by haydenbleasel** [comment]
Hey, yeah a PR would be awesome but I'm trying to figure out if we can avoid a callback and solve this issue in another way. What's the reason behind the custom injection method? Potentially related is #81

**Comment by jraoult** [comment]
I leverage that because the file doesn't exist a this stage, I'm collecting snippets and then assembling them in memory. One possibility would be to give to the `html` option a vinyl file object and then I could merge the content with the other bits.

That said, I feel that a callback is closer to what is going on underneath, simplifies the implementation of the `favicons` module since you don't have to deal with injection specificities / bugs and open the door for custom implementation (a little bit like the https://extensiblewebmanifesto.org/ is trying the foster lower level APIs in the web platform)

**Comment by haydenbleasel** [comment]
Alright yeah, good call. Theoretically your HTML file is meant to exist before running this task but it should be build-agnostic so I'm up for a callback PR :)

**Comment by jraoult** [comment]
Alright then, I'll keep you posted

**Comment by strarsis** [comment]
In first post I read that gulp-favicons is now deprecated?
Can I use favicons directly in gulp standalone?

With best regards

**Comment by jraoult** [comment]
@strarsis you can now use the `stream` method in `favicons`:
```
const stream = require('favicons').stream;

stream({<your settings here>}).pipe(gulp.dest('/build'));
```

**Comment by strarsis** [comment]
Thank you.
A deprecation notice on gulp-favicons would be helpful.

With best regards

**Comment by haydenbleasel** [comment]
@strarsis @jraoult `gulp-favicons` isn't deprecated. I'll update the master readme to be clear.
