### ISSUE TITLE
Images rotated. HTML markup different from file names.

### ISSUE THREAD

**Issue by alanontheweb** [haydenbleasel/favicons#84]
The generated markup for *some* of the graphics such as-
href="assets/img/favicon/apple-touch-startup-image-2048x1496.png"
href="assets/img/favicon/apple-touch-startup-image-1024x748.png"

differ from the file names which are -
apple-touch-startup-image-1496x2048.png
apple-touch-startup-image-748x1024.png

These specifc images are also rotated 90 degrees. Am I missing something? All the rest work fine.

**Comment by alanontheweb** [comment]
Ah easy fix on the html.json

**Comment by haydenbleasel** [comment]
Not your fault I believe. Related issue: #69
