### ISSUE TITLE
Backslashes in browserconfig.xml

### ISSUE THREAD

**Issue by andrey-hohlov** [haydenbleasel/favicons#90]
Hi!

Try to using favicons with gulp.

```
favicons = require('favicons').stream,
```
In options set:
```
path: '/favicons/',
```
In browserconfig.xml get 
```
<square70x70logo src="\favicons\mstile-70x70.png"/>
<square150x150logo src="\favicons\mstile-150x150.png"/>
<wide310x150logo src="\favicons\mstile-310x150.png"/>
<square310x310logo src="\favicons\mstile-310x310.png"/>
```

With backslashes get an error when checking on http://realfavicongenerator.net/favicon_checker

Windows 7, Node v4.2.1, Gulp  3.9.0

**Comment by haydenbleasel** [comment]
Hey @andrey-hohlov, 2 things:

1. You should use the Gulp wrapper: `gulp-favicons`.
2. Are you using the property `online: true`?

**Comment by andrey-hohlov** [comment]
@haydenbleasel, thank you for fast response!

1. Ok, i have install it.
I think be better if we need to install only one.

2. No, I use `online: false`.
If set `true` it works without problem with slashes, but it works slowly: ~ 15-20 second vs. 3 second.

Also, if I understand correctly, setting `true` making request to RealFaviconGenerator. It's bad in case when i need to build my project without internet connection.

**Comment by haydenbleasel** [comment]
@andrey-hohlov Yep you should only use `gulp-favicons` for Gulp projects. It's just a single-line wrapper around `Favicons.Stream` so we can keep all the logic in the main module. Also it's totally fine to keep `online:false`, I just needed to check whether it was a Favicons or RFG issue.

Now I have to figure out why backslashes are appearing for you but not for me :S

**Comment by haydenbleasel** [comment]
@andrey-hohlov I can't efficiently test this as I'm an OSX user, but if you test and create a PR with the following changes:

```js
function relative (directory) {
  return path.join(options.path, directory).replace('\\', '/');
}

function absolute (directory) {
  return path.join(options.url, options.path, directory).replace('\\', '/');
}
```

It could be a solution.

**Comment by andrey-hohlov** [comment]
@haydenbleasel
I've tried with this code and have this result:
```
<square70x70logo src="/favicons\mstile-70x70.png"/>
```

It's works with some modification:

```
function relative(directory) {
    return path.join(options.path, directory).replace(/\\/g, '/');
}
function absolute(directory) {
    return path.join(options.url, options.path, directory).replace(/\\/g, '/');
}
```

**Comment by haydenbleasel** [comment]
Closing this issue for #100
