### ISSUE TITLE
Merge in Gulp README

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/favicons#92]
As per #83 and #90, people are using the streaming API for Gulp instead of the Gulp wrapper. I need to make this clearer in the docs.

**Comment by strarsis** [comment]
When one can use favicons stream (for vinyl fs) directly, 
what are the advantages over using gulp-favicons instead?

**Comment by haydenbleasel** [comment]
None, just helpful to have a Gulp wrapper. Check the code for it, it literally just passes parameters to the Stream API: https://github.com/haydenbleasel/favicons/blob/gulp/index.js
