### ISSUE TITLE
Generate index.html (partial) from scratch

### ISSUE THREAD

**Issue by strarsis** [haydenbleasel/favicons#93]
Is it possible to let favicons generate the index.html from scratch?
I want to include it as partial in jade layout template.

Currently I just specify an empty dummy HTML file - 
it would be even nicer if I could just pass "true" to that option key 
and favicons would generate the HTML file purely from scratch.

Edit: So favicons will populate an empty file with markup 
and further runs will then update the non-empty HTML file. -
But what if the markup template in favicons itself is changed?
Will the existing, outdated markup just stay in the updated HTML file
(replace options would replace existing/known markup elements)?

Thank you and
with best regards

**Comment by haydenbleasel** [comment]
Added in `favicons@4.4.4`. Just specify a filename like `html: 'index.html'` and it'll write a blank file.
