### ISSUE TITLE
Some favicon files in root (/)

### ISSUE THREAD

**Issue by strarsis** [haydenbleasel/favicons#94]
A sub-folder can be specified for the URLs in generated markup.
Some browsers seem to always look the favicon and apple touch icon files up in root (/) of domain first,
resulting in unnecessary lookups
(See https://en.wikipedia.org/wiki/Favicon#Limitations_and_criticism and https://mathiasbynens.be/notes/touch-icons).

So wouldn't it make sense to store some of the files, notably the favicon ico and apple touch icon files in root instead, 
providing an extra option to use absolute paths for just these files?

Thank you and
with best regards

**Comment by haydenbleasel** [comment]
@strarsis This is a good point, the user really shouldn't be able to configure the path of their favicons as they should be located in the root. However, I don't think having a path variable defaulting to root is a bad idea, especially if the user has some edge case where their setup requires favicons in a different folder or something.

**Comment by andrey-hohlov** [comment]
For example, if we use gulp and we need make favicons, store them in `/favicons` and store only favicon.ico in `/`

We can just use [gulp-filter](https://github.com/sindresorhus/gulp-filter).
Filter out only `favicon.ico`, or also filter `apple-touch-icon-*.png` and save them where we need.

In my case i use jade and i don't need generate html by favicons. In other cases you can create one times markup and use it - no reasons to generate it every time.

**Comment by strarsis** [comment]
That's nice, now if we could use some gulp plugin that takes in all the favicon file path, 
all, those in / and those in /favicons, and then generates a HTML file from these paths.

**Comment by haydenbleasel** [comment]
Yep, you can probably use `gulp-filter` and #97.
