### ISSUE TITLE
Further favicon related markup elements

### ISSUE THREAD

**Issue by strarsis** [haydenbleasel/favicons#95]
Before I migrated to favicons for my favicon related markup,
I used the following additional elements:
- application-name
- apple-mobile-web-app-status-bar-style
- apple-mobile-web-app-title

Are they useful enough to be added to favicons markup template?

With best regards

**Comment by haydenbleasel** [comment]
I think they would be useful, however they aren't technically "favicon-related". @phbernard What are your thoughts on this?

**Comment by phbernard** [comment]
These elements are a bit borderline, but yes, I think they deserve to be supported:

  - `application-name` and `apple-mobile-web-app-title`: the `manifest.json` file, supported by Android Chrome, requires an app name. So when you play with multi-platform icons, there is already an app name around. It makes sense to support the equivalent for other platforms.
  - `apple-mobile-web-app-status-bar-style`: this setting looks like a theme color (eg. the tile color of Windows 8), which is in the scope of the icons. And again, there is a similar setting in `manifest.json`, which RFG supports.

**Comment by haydenbleasel** [comment]
Alright well, let's get them implemented :+1:

**Comment by haydenbleasel** [comment]
Added in `favicons@4.4.5`
