### ISSUE TITLE
Incremental builds/gulp-changed support

### ISSUE THREAD

**Issue by strarsis** [haydenbleasel/favicons#96]
Each time I run favicons, it will recreate all image files, etc, 
either online or locally standalone. In both cases this takes time.

Is there a way integrating gulp-changed with (gulp-)favicons?

Thank you and
with best regards

**Comment by haydenbleasel** [comment]
@strarsis Theoretically `gulp-changed` should just work e.g.

```
gulp.task("default", function () {
    gulp.src("logo.png")
        .pipe($.changed(...))
        .pipe($.favicons(...))
        .pipe(gulp.dest("./"));
});
```

**Comment by strarsis** [comment]
Thank you for your response!

gulp-changed requires a destination - what file can I use? The HTML file? All files will change anyway, so I could pick any single file?

With best regards

**Comment by strarsis** [comment]
So I ended up coupling favicon.png (input file) with favicon.ico (one of the output files):
````
return gulp.src('./assets/images/favicon.png')
               .pipe(plugins.changed('./public/images/', { extension: '.ico' }))
````
Though when the favicons task is cancelled for whatever reason then gulp-changed would not detect whether really all files are updated.

With best regards

**Comment by haydenbleasel** [comment]
@strarsis This feature has been added in #97.

**Comment by strarsis** [comment]
How can I access the config object when using gulp-favicons plugin?
An example would be very helpful.
````
var favicons = require('gulp-favicons');
favicons. ?
````

Thank you and
with best regards

**Comment by strarsis** [comment]
Current approach using favicons instead gulp-favicons:
````
[...]
var favicons = require('favicons');
var gulpFavicons = favicons.stream;
var faviconsStream = gulpFavicons({
// [...]
});

var icons = favicons.config.icons;
var faviconsFiles = [];
for(iconName in icons) { var icon = icons[iconName];
  for(file in icon) { faviconsFiles.push(file); }
}
[...]
````

How can I now use it with gulp-changed or gulp-newer?

````
[...]
return gulp.src(srcFaviconPath + '/favicon.png')
               .pipe(changed(/* only accepts a single string (file), not an array of files */))
               .pipe(faviconsStream)
               .pipe(gulp.dest(destFaviconPath));
````

With best regards

**Comment by haydenbleasel** [comment]
@strarsis Config issue for gulp-favicons is here: #102
